# Generated by Django 5.0 on 2024-01-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=122)),
                ('lastName', models.CharField(max_length=122)),
                ('Username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
